### PR TITLE
Compatibility for iOS 9.2/9.3/10+ and automated scripts.

### PR DESCRIPTION
**Pull request by PoomSmart**

### CODE REVIEW

**Comment by gabrielmaldi** [comment]
I can confirm this is working for me with Simulator running iOS 9.3 on OS X 10.11.5.

**Comment by zgavin** [comment]
Can also confirm this is working

**Comment by hotdang-ca** [comment]
Confirmed working Xcode 7.3.1 / 10.11.5 / iOS 9.3

**Comment by alpennec** [comment]
Hello,
I tried on Xcode 8 with iOS 10, it does not work.
Anyone succeeded to have it work?
Thanks
Axel

**Comment by arasu01** [comment]
This is not working for me in Xcode 8.

**Comment by wrozka** [comment]
Works fine with the latest update https://github.com/DeskConnect/SBShortcutMenuSimulator/pull/18/commits/3b9ce590d07876c513742cf01b1eb5748b706bcd

**Comment by gabrielmaldi** [comment]
Anyone willing to merge this in?

**Pull request closed without merging**
